Repository CAMaji/oxygen-cs-grp2-eq10, pull requests merged in 2023-07, with the labels that each got.

#53 [PR] - Docker - Créer une image pour le projet Oxygencs
  Dockerfile
  database/SnapshotDB.py
  database/metrics/kanban/IssueLeadTimeDB.py
  database/metrics/kanban/IssueLeadTimePeriodDB.py
  database/metrics/kanban/IssuesActiveByColumnDB.py
  database/metrics/kanban/IssuesCompletedWithinPeriodDB.py
  database/metrics/pullrequests/PRAvgCommentsDB.py
  database/metrics/pullrequests/PRAvgDelayUntilCommentDB.py
  database/metrics/pullrequests/PRAvgLeadTimeDB.py
  database/metrics/pullrequests/PRLinesCodeDB.py
  database/metrics/pullrequests/PRMergedInPeriodDB.py
  docker-compose.yml
Labels: medium priority, pull request

#52 [FEATURE ] - Ajouter plus de unit tests pour le main
  .pre-commit-config.yaml
  unit_testing/app/test_main.py
Labels: feature, medium priority

#57 [PR] - Fixing temperature controls
  src/main.py
Labels: low priority, pull request

#59 [PR] - Expliquer le fonctionnement de l'intégration continue
  docker-compose.yml
  wiki/pipeline.md
Labels: medium priority, pull request

#60 [PR] - CI Documentation
  docker-compose.yml
  wiki/pipeline.md
Labels: medium priority, pull request

#55 [PR] - More unit tests
  unit_testing/app/test_main.py
  wiki/githooks.md
  wiki/precommit-linting.md
  wiki/variables-environnement.md
Labels: feature, medium priority

#61 [PR] - More unit tests & wiki
  unit_testing/app/test_main.py
  wiki/githooks.md
  wiki/precommit-linting.md
  wiki/variables-environnement.md
Labels: medium priority, pull request
